[package]
authors = ["Dmitriy303"]
description = "ZenithDB"
edition = "2021"
license = "MIT License"
name = "zenithdb"
repository = "https://github.com/TechCraft-Solutions/ZenithDB"
version = "0.1.1"

[lib]
name = "zenithdb_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-opener = "2"
tauri-plugin-dialog = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
dirs = "5"
uuid = { version = "1", features = ["v4"] }
tokio = { version = "1", features = ["full"] }
sysinfo = "0.32"
tauri-plugin-mcp-bridge = "0.11"

nosql_orm = { git = "https://github.com/rusnakdima/nosql_orm", branch = "main", features = [
    "json",
    "mongo",
    "redis",
    "sql-postgres",
    "sql-sqlite",
    "sql-mysql",
    "query_cache",
    "validators",
] }
# nosql_orm = { path = "/mnt/Other/Projects/Rust/nosql_orm", features = [
#     "json",
#     "mongo",
#     "redis",
#     "sql-postgres",
#     "sql-sqlite",
#     "sql-mysql",
#     "query_cache",
#     "validators",
# ] }
rusqlite = { version = "0.33", features = ["bundled"] }
ts-rs = "8"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
tracing-appender = "0.2"
chrono = "0.4"
