name: GitHub Releases to Discord Forum
on:
  release:
    types: [published]

jobs:
  publish-post-discord:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create Discord Forum Post
        run: |
          curl -X POST "${{ secrets.WEBHOOK_URL }}" \
            -H "Authorization: Bot ${{ secrets.DISCORD_BOT_TOKEN }}" \
            -H "Content-Type: application/json" \
            --data '{
              "name": "🚀 ZenithDB (Beta Release ${{ github.event.release.tag_name }})",
              "auto_archive_duration": 4320,
              "message": {
                "content": "**🚀 New Release Available!**\n\n📦 **Version:** ${{ github.event.release.tag_name }}\n🔗 **Download:** ${{ github.event.release.html_url }}\n\n---\n\n**🇷🇺 Русский перевод**\n**🚀 Новая версия доступна!**\n\n📦 **Версия:** ${{ github.event.release.tag_name }}\n🔗 **Скачать:** ${{ github.event.release.html_url }}"
              }
            }' \
            --fail \
            --show-error
